# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
