# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180225_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_me',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_here',
        ),
    ]
